//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.2.2-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SimplePAG.g4 by ANTLR 4.2.2-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using System.Collections.Generic;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.2.2-SNAPSHOT")]
[System.CLSCompliant(false)]
public partial class SimplePAGParser : Parser {
	public const int
		T__12=1, T__11=2, T__10=3, T__9=4, T__8=5, T__7=6, T__6=7, T__5=8, T__4=9, 
		T__3=10, T__2=11, T__1=12, T__0=13, NUMBER=14, INTEGER=15, FLOAT=16, ID=17, 
		WS=18;
	public static readonly string[] tokenNames = {
		"<INVALID>", "'#rules'", "':'", "'['", "';'", "']'", "'()'", "'\"'", "'('", 
		"')'", "'+'", "','", "'-'", "'::-'", "NUMBER", "INTEGER", "FLOAT", "ID", 
		"WS"
	};
	public const int
		RULE_pag = 0, RULE_rules = 1, RULE_rule = 2, RULE_successor = 3, RULE_cmdDefinition = 4, 
		RULE_pushPopScope = 5, RULE_argumentsDefinition = 6, RULE_argumentDefinition = 7, 
		RULE_asset_uri = 8, RULE_shape_name = 9, RULE_unary = 10, RULE_atom = 11;
	public static readonly string[] ruleNames = {
		"pag", "rules", "rule", "successor", "cmdDefinition", "pushPopScope", 
		"argumentsDefinition", "argumentDefinition", "asset_uri", "shape_name", 
		"unary", "atom"
	};

	public override string GrammarFileName { get { return "SimplePAG.g4"; } }

	public override string[] TokenNames { get { return tokenNames; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public SimplePAGParser(ITokenStream input)
		: base(input)
	{
		_interp = new ParserATNSimulator(this,_ATN);
	}
	public partial class PagContext : ParserRuleContext {
		public RulesContext rules() {
			return GetRuleContext<RulesContext>(0);
		}
		public PagContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int GetRuleIndex() { return RULE_pag; }
		public override void EnterRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.EnterPag(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.ExitPag(this);
		}
	}

	[RuleVersion(0)]
	public PagContext pag() {
		PagContext _localctx = new PagContext(_ctx, State);
		EnterRule(_localctx, 0, RULE_pag);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 24; Match(1);
			State = 25; rules();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RulesContext : ParserRuleContext {
		public RuleContext[] rule() {
			return GetRuleContexts<RuleContext>();
		}
		public RuleContext rule(int i) {
			return GetRuleContext<RuleContext>(i);
		}
		public RulesContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int GetRuleIndex() { return RULE_rules; }
		public override void EnterRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.EnterRules(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.ExitRules(this);
		}
	}

	[RuleVersion(0)]
	public RulesContext rules() {
		RulesContext _localctx = new RulesContext(_ctx, State);
		EnterRule(_localctx, 2, RULE_rules);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 28;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 27; rule();
				}
				}
				State = 30;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==ID );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RuleContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(SimplePAGParser.ID, 0); }
		public SuccessorContext successor(int i) {
			return GetRuleContext<SuccessorContext>(i);
		}
		public SuccessorContext[] successor() {
			return GetRuleContexts<SuccessorContext>();
		}
		public ITerminalNode[] FLOAT() { return GetTokens(SimplePAGParser.FLOAT); }
		public ITerminalNode FLOAT(int i) {
			return GetToken(SimplePAGParser.FLOAT, i);
		}
		public RuleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int GetRuleIndex() { return RULE_rule; }
		public override void EnterRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.EnterRule(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.ExitRule(this);
		}
	}

	[RuleVersion(0)]
	public RuleContext rule() {
		RuleContext _localctx = new RuleContext(_ctx, State);
		EnterRule(_localctx, 4, RULE_rule);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 32; Match(ID);
			State = 33; Match(13);
			State = 34; successor();
			State = 37;
			_la = _input.La(1);
			if (_la==2) {
				{
				State = 35; Match(2);
				State = 36; Match(FLOAT);
				}
			}

			State = 46;
			_errHandler.Sync(this);
			_la = _input.La(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << 3) | (1L << 5) | (1L << ID))) != 0)) {
				{
				{
				State = 39; successor();
				State = 42;
				_la = _input.La(1);
				if (_la==2) {
					{
					State = 40; Match(2);
					State = 41; Match(FLOAT);
					}
				}

				}
				}
				State = 48;
				_errHandler.Sync(this);
				_la = _input.La(1);
			}
			State = 49; Match(4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SuccessorContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(SimplePAGParser.ID, 0); }
		public CmdDefinitionContext cmdDefinition() {
			return GetRuleContext<CmdDefinitionContext>(0);
		}
		public SuccessorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int GetRuleIndex() { return RULE_successor; }
		public override void EnterRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.EnterSuccessor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.ExitSuccessor(this);
		}
	}

	[RuleVersion(0)]
	public SuccessorContext successor() {
		SuccessorContext _localctx = new SuccessorContext(_ctx, State);
		EnterRule(_localctx, 6, RULE_successor);
		try {
			State = 53;
			switch ( Interpreter.AdaptivePredict(_input,4,_ctx) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 51; cmdDefinition();
				}
				break;

			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 52; Match(ID);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CmdDefinitionContext : ParserRuleContext {
		public PushPopScopeContext pushPopScope() {
			return GetRuleContext<PushPopScopeContext>(0);
		}
		public ITerminalNode ID() { return GetToken(SimplePAGParser.ID, 0); }
		public ArgumentsDefinitionContext argumentsDefinition() {
			return GetRuleContext<ArgumentsDefinitionContext>(0);
		}
		public CmdDefinitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int GetRuleIndex() { return RULE_cmdDefinition; }
		public override void EnterRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.EnterCmdDefinition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.ExitCmdDefinition(this);
		}
	}

	[RuleVersion(0)]
	public CmdDefinitionContext cmdDefinition() {
		CmdDefinitionContext _localctx = new CmdDefinitionContext(_ctx, State);
		EnterRule(_localctx, 8, RULE_cmdDefinition);
		try {
			State = 58;
			switch (_input.La(1)) {
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 55; Match(ID);
				State = 56; argumentsDefinition();
				}
				break;
			case 3:
			case 5:
				EnterOuterAlt(_localctx, 2);
				{
				State = 57; pushPopScope();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PushPopScopeContext : ParserRuleContext {
		public PushPopScopeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int GetRuleIndex() { return RULE_pushPopScope; }
		public override void EnterRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.EnterPushPopScope(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.ExitPushPopScope(this);
		}
	}

	[RuleVersion(0)]
	public PushPopScopeContext pushPopScope() {
		PushPopScopeContext _localctx = new PushPopScopeContext(_ctx, State);
		EnterRule(_localctx, 10, RULE_pushPopScope);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 60;
			_la = _input.La(1);
			if ( !(_la==3 || _la==5) ) {
			_errHandler.RecoverInline(this);
			}
			Consume();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentsDefinitionContext : ParserRuleContext {
		public ArgumentDefinitionContext argumentDefinition(int i) {
			return GetRuleContext<ArgumentDefinitionContext>(i);
		}
		public ArgumentDefinitionContext[] argumentDefinition() {
			return GetRuleContexts<ArgumentDefinitionContext>();
		}
		public ArgumentsDefinitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int GetRuleIndex() { return RULE_argumentsDefinition; }
		public override void EnterRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.EnterArgumentsDefinition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.ExitArgumentsDefinition(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentsDefinitionContext argumentsDefinition() {
		ArgumentsDefinitionContext _localctx = new ArgumentsDefinitionContext(_ctx, State);
		EnterRule(_localctx, 12, RULE_argumentsDefinition);
		int _la;
		try {
			State = 74;
			switch (_input.La(1)) {
			case 8:
				EnterOuterAlt(_localctx, 1);
				{
				State = 62; Match(8);
				State = 63; argumentDefinition();
				State = 68;
				_errHandler.Sync(this);
				_la = _input.La(1);
				while (_la==11) {
					{
					{
					State = 64; Match(11);
					State = 65; argumentDefinition();
					}
					}
					State = 70;
					_errHandler.Sync(this);
					_la = _input.La(1);
				}
				State = 71; Match(9);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 2);
				{
				State = 73; Match(6);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentDefinitionContext : ParserRuleContext {
		public Shape_nameContext shape_name() {
			return GetRuleContext<Shape_nameContext>(0);
		}
		public UnaryContext unary() {
			return GetRuleContext<UnaryContext>(0);
		}
		public ArgumentDefinitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int GetRuleIndex() { return RULE_argumentDefinition; }
		public override void EnterRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.EnterArgumentDefinition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.ExitArgumentDefinition(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentDefinitionContext argumentDefinition() {
		ArgumentDefinitionContext _localctx = new ArgumentDefinitionContext(_ctx, State);
		EnterRule(_localctx, 14, RULE_argumentDefinition);
		try {
			State = 78;
			switch (_input.La(1)) {
			case 10:
			case 12:
			case NUMBER:
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 76; unary();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 2);
				{
				State = 77; shape_name();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Asset_uriContext : ParserRuleContext {
		public ITerminalNode[] ID() { return GetTokens(SimplePAGParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(SimplePAGParser.ID, i);
		}
		public Asset_uriContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int GetRuleIndex() { return RULE_asset_uri; }
		public override void EnterRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.EnterAsset_uri(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.ExitAsset_uri(this);
		}
	}

	[RuleVersion(0)]
	public Asset_uriContext asset_uri() {
		Asset_uriContext _localctx = new Asset_uriContext(_ctx, State);
		EnterRule(_localctx, 16, RULE_asset_uri);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 80; Match(7);
			State = 81; Match(ID);
			State = 86;
			_errHandler.Sync(this);
			_la = _input.La(1);
			while (_la==2) {
				{
				{
				State = 82; Match(2);
				State = 83; Match(ID);
				}
				}
				State = 88;
				_errHandler.Sync(this);
				_la = _input.La(1);
			}
			State = 89; Match(7);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Shape_nameContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(SimplePAGParser.ID, 0); }
		public Shape_nameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int GetRuleIndex() { return RULE_shape_name; }
		public override void EnterRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.EnterShape_name(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.ExitShape_name(this);
		}
	}

	[RuleVersion(0)]
	public Shape_nameContext shape_name() {
		Shape_nameContext _localctx = new Shape_nameContext(_ctx, State);
		EnterRule(_localctx, 18, RULE_shape_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 91; Match(7);
			State = 92; Match(ID);
			State = 93; Match(7);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnaryContext : ParserRuleContext {
		public AtomContext atom() {
			return GetRuleContext<AtomContext>(0);
		}
		public UnaryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int GetRuleIndex() { return RULE_unary; }
		public override void EnterRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.EnterUnary(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.ExitUnary(this);
		}
	}

	[RuleVersion(0)]
	public UnaryContext unary() {
		UnaryContext _localctx = new UnaryContext(_ctx, State);
		EnterRule(_localctx, 20, RULE_unary);
		try {
			State = 100;
			switch (_input.La(1)) {
			case 12:
				EnterOuterAlt(_localctx, 1);
				{
				State = 95; Match(12);
				State = 96; atom();
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 2);
				{
				State = 97; Match(10);
				State = 98; atom();
				}
				break;
			case NUMBER:
			case ID:
				EnterOuterAlt(_localctx, 3);
				{
				State = 99; atom();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AtomContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(SimplePAGParser.ID, 0); }
		public ITerminalNode NUMBER() { return GetToken(SimplePAGParser.NUMBER, 0); }
		public AtomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int GetRuleIndex() { return RULE_atom; }
		public override void EnterRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.EnterAtom(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimplePAGListener typedListener = listener as ISimplePAGListener;
			if (typedListener != null) typedListener.ExitAtom(this);
		}
	}

	[RuleVersion(0)]
	public AtomContext atom() {
		AtomContext _localctx = new AtomContext(_ctx, State);
		EnterRule(_localctx, 22, RULE_atom);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 102;
			_la = _input.La(1);
			if ( !(_la==NUMBER || _la==ID) ) {
			_errHandler.RecoverInline(this);
			}
			Consume();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public static readonly string _serializedATN =
		"\x3\xAF6F\x8320\x479D\xB75C\x4880\x1605\x191C\xAB37\x3\x14k\x4\x2\t\x2"+
		"\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a\t\a\x4\b\t\b\x4\t\t"+
		"\t\x4\n\t\n\x4\v\t\v\x4\f\t\f\x4\r\t\r\x3\x2\x3\x2\x3\x2\x3\x3\x6\x3\x1F"+
		"\n\x3\r\x3\xE\x3 \x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x5\x4(\n\x4\x3\x4\x3\x4"+
		"\x3\x4\x5\x4-\n\x4\a\x4/\n\x4\f\x4\xE\x4\x32\v\x4\x3\x4\x3\x4\x3\x5\x3"+
		"\x5\x5\x5\x38\n\x5\x3\x6\x3\x6\x3\x6\x5\x6=\n\x6\x3\a\x3\a\x3\b\x3\b\x3"+
		"\b\x3\b\a\b\x45\n\b\f\b\xE\bH\v\b\x3\b\x3\b\x3\b\x5\bM\n\b\x3\t\x3\t\x5"+
		"\tQ\n\t\x3\n\x3\n\x3\n\x3\n\a\nW\n\n\f\n\xE\nZ\v\n\x3\n\x3\n\x3\v\x3\v"+
		"\x3\v\x3\v\x3\f\x3\f\x3\f\x3\f\x3\f\x5\fg\n\f\x3\r\x3\r\x3\r\x2\x2\x2"+
		"\xE\x2\x2\x4\x2\x6\x2\b\x2\n\x2\f\x2\xE\x2\x10\x2\x12\x2\x14\x2\x16\x2"+
		"\x18\x2\x2\x4\x4\x2\x5\x5\a\a\x4\x2\x10\x10\x13\x13j\x2\x1A\x3\x2\x2\x2"+
		"\x4\x1E\x3\x2\x2\x2\x6\"\x3\x2\x2\x2\b\x37\x3\x2\x2\x2\n<\x3\x2\x2\x2"+
		"\f>\x3\x2\x2\x2\xEL\x3\x2\x2\x2\x10P\x3\x2\x2\x2\x12R\x3\x2\x2\x2\x14"+
		"]\x3\x2\x2\x2\x16\x66\x3\x2\x2\x2\x18h\x3\x2\x2\x2\x1A\x1B\a\x3\x2\x2"+
		"\x1B\x1C\x5\x4\x3\x2\x1C\x3\x3\x2\x2\x2\x1D\x1F\x5\x6\x4\x2\x1E\x1D\x3"+
		"\x2\x2\x2\x1F \x3\x2\x2\x2 \x1E\x3\x2\x2\x2 !\x3\x2\x2\x2!\x5\x3\x2\x2"+
		"\x2\"#\a\x13\x2\x2#$\a\xF\x2\x2$\'\x5\b\x5\x2%&\a\x4\x2\x2&(\a\x12\x2"+
		"\x2\'%\x3\x2\x2\x2\'(\x3\x2\x2\x2(\x30\x3\x2\x2\x2),\x5\b\x5\x2*+\a\x4"+
		"\x2\x2+-\a\x12\x2\x2,*\x3\x2\x2\x2,-\x3\x2\x2\x2-/\x3\x2\x2\x2.)\x3\x2"+
		"\x2\x2/\x32\x3\x2\x2\x2\x30.\x3\x2\x2\x2\x30\x31\x3\x2\x2\x2\x31\x33\x3"+
		"\x2\x2\x2\x32\x30\x3\x2\x2\x2\x33\x34\a\x6\x2\x2\x34\a\x3\x2\x2\x2\x35"+
		"\x38\x5\n\x6\x2\x36\x38\a\x13\x2\x2\x37\x35\x3\x2\x2\x2\x37\x36\x3\x2"+
		"\x2\x2\x38\t\x3\x2\x2\x2\x39:\a\x13\x2\x2:=\x5\xE\b\x2;=\x5\f\a\x2<\x39"+
		"\x3\x2\x2\x2<;\x3\x2\x2\x2=\v\x3\x2\x2\x2>?\t\x2\x2\x2?\r\x3\x2\x2\x2"+
		"@\x41\a\n\x2\x2\x41\x46\x5\x10\t\x2\x42\x43\a\r\x2\x2\x43\x45\x5\x10\t"+
		"\x2\x44\x42\x3\x2\x2\x2\x45H\x3\x2\x2\x2\x46\x44\x3\x2\x2\x2\x46G\x3\x2"+
		"\x2\x2GI\x3\x2\x2\x2H\x46\x3\x2\x2\x2IJ\a\v\x2\x2JM\x3\x2\x2\x2KM\a\b"+
		"\x2\x2L@\x3\x2\x2\x2LK\x3\x2\x2\x2M\xF\x3\x2\x2\x2NQ\x5\x16\f\x2OQ\x5"+
		"\x14\v\x2PN\x3\x2\x2\x2PO\x3\x2\x2\x2Q\x11\x3\x2\x2\x2RS\a\t\x2\x2SX\a"+
		"\x13\x2\x2TU\a\x4\x2\x2UW\a\x13\x2\x2VT\x3\x2\x2\x2WZ\x3\x2\x2\x2XV\x3"+
		"\x2\x2\x2XY\x3\x2\x2\x2Y[\x3\x2\x2\x2ZX\x3\x2\x2\x2[\\\a\t\x2\x2\\\x13"+
		"\x3\x2\x2\x2]^\a\t\x2\x2^_\a\x13\x2\x2_`\a\t\x2\x2`\x15\x3\x2\x2\x2\x61"+
		"\x62\a\xE\x2\x2\x62g\x5\x18\r\x2\x63\x64\a\f\x2\x2\x64g\x5\x18\r\x2\x65"+
		"g\x5\x18\r\x2\x66\x61\x3\x2\x2\x2\x66\x63\x3\x2\x2\x2\x66\x65\x3\x2\x2"+
		"\x2g\x17\x3\x2\x2\x2hi\t\x3\x2\x2i\x19\x3\x2\x2\x2\r \',\x30\x37<\x46"+
		"LPX\x66";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
