//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.2.2-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SimplePAG.g4 by ANTLR 4.2.2-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SimplePAGParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.2.2-SNAPSHOT")]
[System.CLSCompliant(false)]
public interface ISimplePAGListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimplePAGParser.argumentsDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentsDefinition([NotNull] SimplePAGParser.ArgumentsDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimplePAGParser.argumentsDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentsDefinition([NotNull] SimplePAGParser.ArgumentsDefinitionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SimplePAGParser.cmdDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmdDefinition([NotNull] SimplePAGParser.CmdDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimplePAGParser.cmdDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmdDefinition([NotNull] SimplePAGParser.CmdDefinitionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SimplePAGParser.successor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSuccessor([NotNull] SimplePAGParser.SuccessorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimplePAGParser.successor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSuccessor([NotNull] SimplePAGParser.SuccessorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SimplePAGParser.argumentDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentDefinition([NotNull] SimplePAGParser.ArgumentDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimplePAGParser.argumentDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentDefinition([NotNull] SimplePAGParser.ArgumentDefinitionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SimplePAGParser.pag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPag([NotNull] SimplePAGParser.PagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimplePAGParser.pag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPag([NotNull] SimplePAGParser.PagContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SimplePAGParser.asset_uri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsset_uri([NotNull] SimplePAGParser.Asset_uriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimplePAGParser.asset_uri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsset_uri([NotNull] SimplePAGParser.Asset_uriContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SimplePAGParser.shape_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShape_name([NotNull] SimplePAGParser.Shape_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimplePAGParser.shape_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShape_name([NotNull] SimplePAGParser.Shape_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SimplePAGParser.rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule([NotNull] SimplePAGParser.RuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimplePAGParser.rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule([NotNull] SimplePAGParser.RuleContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SimplePAGParser.rules"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRules([NotNull] SimplePAGParser.RulesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimplePAGParser.rules"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRules([NotNull] SimplePAGParser.RulesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SimplePAGParser.floating_point"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloating_point([NotNull] SimplePAGParser.Floating_pointContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimplePAGParser.floating_point"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloating_point([NotNull] SimplePAGParser.Floating_pointContext context);
}
